version: '3.7'
services:
  web:
    build: .
    command: ./docker-start.sh
    volumes:
      - .:/app
      - bundles:/bundles
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app
    volumes:
      - datastore:/var/lib/postgresql/data
    ports:
      - "5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment: 
      - "discovery.type=single-node"
    ports: 
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    environment: 
     - ELASTICSEARCH_URL=http://elasticsearch:9200
    # volumes: 
    # - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports: 
      - "5601:5601"
volumes:
  bundles:
  datastore:
